# DevSecOps Tarea Final -Diego Valdes
name:   DevSecOps - CICD

on:
  push:
    branches:
      - feature-devsecops

jobs:
  JTRPipeline:
    runs-on: ubuntu-latest
    steps:
      # 1. Clonación de repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Repositorio clonado
        run: |
          echo "::notice title=Clonación Exitosa::Repositorio ${{ github.repository }} clonado correctamente"
          echo "Iniciando pipeline DevSecOps ${{ github.event.repository.name }}"
