# DevSecOps Tarea Final -Diego Valdes
name:   DevSecOps - CICD

on:
  push:
    branches:
      - feature-devsecops

jobs:
  JTRPipeline:
    runs-on: ubuntu-latest
    steps:
      # 1. Clonación de repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Repositorio clonado
        run: |
          echo "::notice title=Clonación Exitosa::Repositorio ${{ github.repository }} clonado correctamente"
          echo "Iniciando pipeline DevSecOps ${{ github.event.repository.name }}"
          
        # 2. Validar  proyecto en SonarCloud
      - name: Validando existencia de Proyecto en Sonarcloud
        id: validateProjectSonar
        run: |
          curl -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/projects/create' -d 'name=${{github.event.repository.name}}' -d 'organization=DValMen' -d 'project=${{github.event.repository.name}}' -d 'visibility=public'
          if [ $? -eq 0 ]; then
            echo "Proyecto creado o ya existe en SonarCloud"
            curl -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/project_branches/rename' -d 'name=main' -d 'project=${{github.event.repository.name}}'
          else
            echo "Error al crear el proyecto en SonarCloud"
            exit 1
          fi
